const GET_TEAM = "reducers/aboutUs/GET_TEAM";
const GET_TEAM_FULFILLED = "reducers/aboutUs/GET_TEAM_FULFILLED";
const GET_TEAM_REJECTED = "reducers/aboutUs/GET_TEAM_REJECTED";
export { GET_TEAM, GET_TEAM_FULFILLED, GET_TEAM_REJECTED };
export var STATUS_TYPE;
(function (STATUS_TYPE) {
    STATUS_TYPE["FULFILLED"] = "FULFILLED";
    STATUS_TYPE["PENDING"] = "PENDING";
    STATUS_TYPE["REJECTED"] = "REJECTED";
    STATUS_TYPE["UNINITIALIZED"] = "UNINITIALIZED";
})(STATUS_TYPE || (STATUS_TYPE = {}));
